# Store configurations for grocery price scanning

stores:
  metro_ca:
    name: "Metro"
    base_url: "https://www.metro.ca"
    currency: "CAD"
    search_url_template: "https://www.metro.ca/en/online-grocery/search?filter={query}"
    rate_limit_seconds: 2.0
    max_retries: 3
    timeout_seconds: 30
    active: true
    
    selectors:
      product_container: ".product-tile"
      product_name: ".product-name"
      price: ".price-update"
      brand: ".product-brand"
      image: ".product-image img"
      product_link: ".product-tile-inner a"
      out_of_stock: ".out-of-stock"
      on_sale: ".price-reduction"
    
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate"
      Connection: "keep-alive"
    
    postal_code: "M5V 3A8"  # Toronto downtown
    delivery_available: true

  walmart_ca:
    name: "Walmart Canada"
    base_url: "https://www.walmart.ca"
    currency: "CAD"
    search_url_template: "https://www.walmart.ca/en/grocery/search?q={query}"
    rate_limit_seconds: 1.5
    max_retries: 3
    timeout_seconds: 30
    active: true
    
    selectors:
      product_container: ".product-item"
      product_name: ".product-name"
      price: ".price-current"
      brand: ".product-brand"
      image: ".product-image img"
      product_link: ".product-item a"
      out_of_stock: ".out-of-stock"
      on_sale: ".price-reduced"
    
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-CA,en;q=0.5"
    
    postal_code: "M5V 3A8"
    delivery_available: true

  freshco_com:
    name: "FreshCo"
    base_url: "https://www.freshco.com"
    currency: "CAD"
    search_url_template: "https://www.freshco.com/search?q={query}"
    rate_limit_seconds: 2.5
    max_retries: 3
    timeout_seconds: 30
    active: true
    
    selectors:
      product_container: ".product-card"
      product_name: ".product-title"
      price: ".price"
      brand: ".brand-name"
      image: ".product-image img"
      product_link: ".product-card a"
      out_of_stock: ".unavailable"
      on_sale: ".sale-badge"
    
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-CA,en;q=0.5"
    
    postal_code: "M5V 3A8"
    delivery_available: false

# Global settings
global_settings:
  default_timeout: 30
  default_rate_limit: 1.0
  max_concurrent_requests: 5
  retry_backoff_factor: 2.0
  cache_duration_hours: 24